"""Integration tests for ``sphinx_examples_as_code_conf['gallery_downloads']``.

Builds a real sphinx-gallery site (not a hand-built doctree) to confirm the
opt-in gallery mode behaves correctly against sphinx-gallery's actual output,
complementing the hand-built-doctree unit tests in
``test_sphinx_examples_as_code.py``.
"""

from __future__ import annotations

import json
from pathlib import Path
import shutil
import subprocess
import sys

import nbformat
import pytest
from test_tinypages import _run_sphinx_build
from test_tinypages import _sphinx_build_cmd

import sphinx_examples_as_code as seac

FIXTURE_DIR = Path(__file__).parent / 'gallery_fixture'

# Markers unique to sphinx-gallery's own injected note/footer/timing/signature
# -- see gen_rst.py's EXAMPLE_HEADER/DOWNLOAD_LINKS_HEADER/TIMING_CONTENT/SPHX_GLR_SIG.
# The download-UI markers get removed from the page entirely (replaced by our
# own link); the timing/signature markers stay on the rendered page and are
# only ever excluded from the *generated* download file.
_GALLERY_DOWNLOAD_UI_MARKERS = (
    'sphx-glr-download-link-note',
    'sphx-glr-footer',
)
_GALLERY_KEPT_ON_PAGE_MARKERS = (
    'sphx-glr-timing',
    'sphx-glr-signature',
    'Total running time',
    'Gallery generated by Sphinx-Gallery',
)
_GALLERY_FURNITURE_MARKERS = _GALLERY_DOWNLOAD_UI_MARKERS + _GALLERY_KEPT_ON_PAGE_MARKERS


def _build(tmp_path: Path, *, gallery_downloads: bool | None) -> tuple[int, str, str, Path]:
    # Copy the fixture rather than building from it in place: sphinx-gallery
    # writes its generated .rst files *into* examples_dirs' sibling
    # gallery_dirs (i.e. into the source tree itself) as a side effect of
    # building, which would otherwise pollute the checked-out repo.
    src_dir = tmp_path / 'src'
    shutil.copytree(FIXTURE_DIR, src_dir)

    html_dir = tmp_path / 'html'
    doctree_dir = tmp_path / 'doctrees'
    sphinx_args = ()
    if gallery_downloads is not None:
        # bool sub-values need '0'/'1' spelling via -D, not 'True'/'False' --
        # see _coerce_conf_value, which is what actually parses this string
        # (Sphinx's own -D type coercion never applies to dict sub-keys).
        flag = '1' if gallery_downloads else '0'
        sphinx_args = ('-D', f'sphinx_examples_as_code_conf.gallery_downloads={flag}')
    returncode, out, err = _run_sphinx_build(
        _sphinx_build_cmd(src_dir, html_dir, doctree_dir, sphinx_args)
    )
    return returncode, out, err, html_dir


def _is_ours(path: Path) -> bool:
    """Distinguish our generated file from sphinx-gallery's own same-named one.

    Both write a ``plot_minimal.py``/``.ipynb`` under ``_downloads/<digest>/``
    -- ours is identifiable structurally, by the title+underline header this
    extension always starts a generated file with (its first two lines in
    ``.py``, or its first markdown cell's first two lines in ``.ipynb``): a
    title line followed by a line of dashes matching that title's length.
    Gallery mode uses the page's own title there now rather than a fixed
    "# Examples from ..." prefix, so this can't just check for one fixed
    string the way it used to.
    """
    if path.suffix == '.py':
        lines = path.read_text(encoding='utf-8').splitlines()
    else:
        cells = json.loads(path.read_text(encoding='utf-8'))['cells']
        # markdown lines carry a trailing hard-break "  " -- strip it before comparing
        lines = (
            [line.rstrip() for line in ''.join(cells[0]['source']).splitlines()] if cells else []
        )

    if len(lines) < 2:
        return False
    title, underline = lines[0], lines[1]
    if path.suffix == '.py':
        title, underline = title.removeprefix('# '), underline.removeprefix('# ')
    return bool(title) and underline == '-' * len(title)


def test_gallery_downloads_disabled_by_default(tmp_path: Path):
    """With the feature off, sphinx-gallery's own note/footer/timing/signature stay put."""
    returncode, out, err, html_dir = _build(tmp_path, gallery_downloads=None)
    assert returncode == 0, f'sphinx build failed with stdout:\n{out}\nstderr:\n{err}\n'

    html = (html_dir / 'auto_examples' / 'plot_minimal.html').read_text(encoding='utf-8')
    for marker in _GALLERY_FURNITURE_MARKERS:
        assert marker in html, f'{marker!r} unexpectedly missing with the feature disabled'

    # our extension never touched this page, so none of its downloads are "ours"
    downloads_dir = html_dir / '_downloads'
    assert not any(_is_ours(p) for p in downloads_dir.rglob('*.py'))


@pytest.fixture(scope='module')
def gallery_build(tmp_path_factory) -> tuple[Path, str]:
    """Build once with the feature enabled; shared by every enabled-mode test below."""
    tmp_path = tmp_path_factory.mktemp('sphinx_examples_as_code_gallery_build')
    returncode, out, err, html_dir = _build(tmp_path, gallery_downloads=True)
    assert returncode == 0, f'sphinx build failed with stdout:\n{out}\nstderr:\n{err}\n'
    html = (html_dir / 'auto_examples' / 'plot_minimal.html').read_text(encoding='utf-8')
    return html_dir, html


def test_gallery_downloads_enabled_strips_download_ui(gallery_build: tuple[Path, str]):
    _html_dir, html = gallery_build
    for marker in _GALLERY_DOWNLOAD_UI_MARKERS:
        assert marker not in html, f'{marker!r} should have been stripped'


def test_gallery_downloads_enabled_keeps_timing_and_signature_on_page(
    gallery_build: tuple[Path, str],
):
    # per explicit request: these stay visible on the rendered page even
    # with gallery mode on -- only the generated download file excludes them
    _html_dir, html = gallery_build
    for marker in _GALLERY_KEPT_ON_PAGE_MARKERS:
        assert marker in html, f'{marker!r} should still be on the rendered page'


def test_gallery_downloads_enabled_inserts_our_own_links(gallery_build: tuple[Path, str]):
    _html_dir, html = gallery_build
    assert 'Download Python source code' in html
    assert 'Download Jupyter notebook' in html


def _generated(html_dir: Path, suffix: str) -> Path:
    matches = [p for p in (html_dir / '_downloads').rglob(f'*{suffix}') if _is_ours(p)]
    assert len(matches) == 1, f'expected exactly one generated {suffix}, got {matches}'
    return matches[0]


def test_gallery_downloads_py_content(gallery_build: tuple[Path, str]):
    html_dir, _html = gallery_build
    src = _generated(html_dir, '.py').read_text(encoding='utf-8')

    # the page's own title, not a generic "Examples from <docname>" header
    assert src.startswith(
        '# A minimal gallery example\n# ' + '-' * len('A minimal gallery example')
    )
    assert 'x = 1' in src
    assert 'y = 2' in src
    assert 'print(x + y)' in src

    # the user's own note (unrelated to sphinx-gallery's injected one)
    assert '# NOTE:' in src
    assert 'This is a note written inside the gallery example itself.' in src

    # the "%%" cell's prose
    assert 'Some prose in its own cell' in src

    # regression check: a "# %%" cell with its own heading becomes a
    # *sibling* section at the document level, not nested inside the page's
    # own section -- its code must not be silently dropped
    assert '# A headed cell' in src
    assert 'z = 3' in src
    assert 'print(z)' in src

    # captured stdout ("3") from actually running the script must not leak in,
    # nor any sphinx-gallery furniture text
    assert '# 3' not in src
    for marker in _GALLERY_FURNITURE_MARKERS:
        assert marker not in src


def test_gallery_downloads_sibling_section_heading_is_set_off(gallery_build: tuple[Path, str]):
    """The sibling section's own heading gets underline + blank-line treatment.

    Not plain comment text melting into the prose that follows it -- matches
    the file's own header style (see the .ipynb counterpart below, where the
    same underline is what makes it render as a real Markdown heading).
    """
    html_dir, _html = gallery_build
    lines = _generated(html_dir, '.py').read_text(encoding='utf-8').splitlines()

    heading_idx = lines.index('# A headed cell')
    assert lines[heading_idx - 1] == ''  # blank line before the heading
    assert lines[heading_idx + 1] == '# ' + '-' * len('A headed cell')
    assert lines[heading_idx + 2] == ''  # blank line after the heading


def test_gallery_downloads_ipynb_is_valid(gallery_build: tuple[Path, str]):
    html_dir, _html = gallery_build
    nb_path = _generated(html_dir, '.ipynb')
    node = nbformat.read(nb_path, as_version=4)
    nbformat.validate(node)

    text = json.loads(nb_path.read_text(encoding='utf-8'))
    all_source = ''.join(''.join(cell['source']) for cell in text['cells'])
    assert 'x = 1' in all_source
    assert 'print(x + y)' in all_source
    assert 'z = 3' in all_source  # from the sibling ("# %%" headed) section


def test_gallery_downloads_footer_is_its_own_dedicated_ipynb_cell(gallery_build: tuple[Path, str]):
    """Since the footer directly follows a code cell here, it starts a new one.

    Confirms the separator (see test_tinypages.py for the "shares a cell"
    case) can also be a cell's very first line, not just mid-cell.
    """
    html_dir, _html = gallery_build
    notebook = json.loads(_generated(html_dir, '.ipynb').read_text(encoding='utf-8'))
    footer_cell = notebook['cells'][-1]
    assert footer_cell['cell_type'] == 'markdown'
    first_line = footer_cell['source'][0].rstrip()
    assert first_line == seac._FOOTER_SEPARATOR


def test_gallery_downloads_sibling_section_heading_is_markdown_in_ipynb(
    gallery_build: tuple[Path, str],
):
    """The same underline treatment is what makes it a real Markdown heading here."""
    html_dir, _html = gallery_build
    notebook = json.loads(_generated(html_dir, '.ipynb').read_text(encoding='utf-8'))
    heading_cell = next(
        c
        for c in notebook['cells']
        if c['cell_type'] == 'markdown' and 'A headed cell' in ''.join(c['source'])
    )
    source = ''.join(heading_cell['source'])
    assert '-' * len('A headed cell') in source  # setext underline


def test_gallery_downloads_generated_py_executes(gallery_build: tuple[Path, str]):
    """The key correctness check: the generated script must actually run."""
    html_dir, _html = gallery_build
    py_path = _generated(html_dir, '.py')
    result = subprocess.run(
        [sys.executable, str(py_path)],
        capture_output=True,
        text=True,
        timeout=60,
        cwd=py_path.parent,
        check=False,
    )
    assert result.returncode == 0, f'{result.stdout}\n{result.stderr}'
