"""Generate downloadable Python/Jupyter files from docstring "Examples" sections.

See the README for configuration options and the full conversion rules.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass
from dataclasses import replace
import hashlib
import json
from pathlib import Path
import re
from typing import TYPE_CHECKING
from urllib.parse import urljoin
from urllib.parse import urlsplit

from docutils import nodes
from docutils.core import publish_doctree
from sphinx import addnodes
from sphinx.errors import ConfigError

from ._version import __version__

if TYPE_CHECKING:
    from collections.abc import Iterator

    from sphinx.application import Sphinx
    from sphinx.config import Config

# Node types marking the start of another section - bound the end of an
# Examples span. Includes desc/index -- numpydoc renders a class's members
# as flat siblings inside the same desc_content as its Examples section.
_BOUNDARY_TYPES = (
    nodes.rubric,
    nodes.title,
    nodes.section,
    addnodes.desc,
    addnodes.index,
)

# Node types with no textual content worth keeping under any circumstance.
_IGNORED_TYPES = (nodes.image, nodes.figure, nodes.comment, nodes.raw)

# Containers matched by CSS class rather than node type. Dropped from the
# generated download only -- the doctree itself, and so the rendered page,
# is left untouched:
# - sd-dropdown / sd-tab-set (sphinx-design)
# - sphx-glr-script-out (sphinx-gallery, gallery mode only): captured stdout
#   from running the script
# - sphx-glr-timing (sphinx-gallery): "Total running time"
# - sphx-glr-signature (sphinx-gallery): "Generated by Sphinx-Gallery"
# - tags (sphinx-tags): the "Tags: foo, bar" line
_SKIP_SUBTREE_CLASSES = (
    'sd-dropdown',
    'sd-tab-set',
    'sphx-glr-script-out',
    'sphx-glr-timing',
    'sphx-glr-signature',
    'tags',
)

#: Recursed into with no special formatting -- pure structural wrappers.
#: Bullet/enumerated lists and definitions get their own handling instead
#: (see ``_list_segment``/``_definition_segment``).
_CONTAINER_TYPES = (
    nodes.definition_list,
    nodes.definition_list_item,
    nodes.term,
    nodes.classifier,
    nodes.block_quote,
    nodes.container,
    nodes.compound,
    addnodes.versionmodified,
)

# Fixed-label admonitions (.. note::, .. warning::, .. seealso::, ...) - as
# opposed to the generic .. admonition:: Custom Title, handled separately.
_ADMONITION_LABELS = {
    nodes.attention: 'ATTENTION',
    nodes.caution: 'CAUTION',
    nodes.danger: 'DANGER',
    nodes.error: 'ERROR',
    nodes.hint: 'HINT',
    nodes.important: 'IMPORTANT',
    nodes.note: 'NOTE',
    addnodes.seealso: 'SEE ALSO',
    nodes.tip: 'TIP',
    nodes.warning: 'WARNING',
}

_PYTHON_LANGUAGES = ('python', 'py', 'python3')

# A chunk of generated lines tagged with how it should be spaced relative to
# its neighbors when segments are joined (see ``_join_segments``):
#   'code'      real Python source
#   'text'      a plain comment (prose, a paragraph, ...)
#   'directive' a comment block that must be visually set off with a blank
#               line both before and after it (the title header; a
#               ``# NOTE:``-style admonition block)
Segment = tuple[str, list[str]]

# Replacements for non-ASCII chars
ASCII_REPLACEMENTS = str.maketrans(
    {
        '\u2018': "'",  # LEFT SINGLE QUOTATION MARK
        '\u2019': "'",  # RIGHT SINGLE QUOTATION MARK
        '\u201c': '"',  # LEFT DOUBLE QUOTATION MARK
        '\u201d': '"',  # RIGHT DOUBLE QUOTATION MARK
    }
)


def _has_class(node: nodes.Node, css_class: str) -> bool:
    getter = getattr(node, 'get', None)
    return bool(getter) and css_class in getter('classes', [])


def _is_examples_heading(node: nodes.Node) -> bool:
    """Check whether ``node`` is a heading (rubric or title) named "Examples"."""
    return (
        isinstance(node, (nodes.rubric, nodes.title))
        and node.astext().strip().lower() == 'examples'
    )


def _is_see_also_heading(node: nodes.Node) -> bool:
    r"""Check whether ``node`` is a heading (rubric or title) named "See Also".

    Two written forms: a bare ``.. rubric:: See Also`` (flat sibling), or
    ``See Also\\n--------`` underline text (docutils nests it as a section).
    Both get the same treatment as a ``.. seealso::`` directive.
    """
    return (
        isinstance(node, (nodes.rubric, nodes.title))
        and node.astext().strip().lower() == 'see also'
    )


def _is_see_also_section(node: nodes.Node) -> bool:
    """Check whether ``node`` is a nested section titled "See Also"."""
    return (
        isinstance(node, nodes.section)
        and bool(node.children)
        and _is_see_also_heading(node.children[0])
    )


@dataclass(frozen=True)
class _RenderContext:
    """State threaded through the conversion functions for one output format."""

    app: Sphinx
    docname: str
    fmt: str  # 'py' or 'ipynb'
    in_see_also: bool = False
    in_footer: bool = False
    show_see_also: bool = True


def _normalized_html_baseurl(app: Sphinx) -> str | None:
    """Sphinx's own ``html_baseurl`` config, normalized for use with ``urljoin``.

    ``None`` if unset or not a usable absolute URL. Adds a missing trailing
    slash.
    """
    base_url = app.config.html_baseurl
    if not base_url:
        return None
    parsed = urlsplit(base_url)
    if parsed.scheme not in ('http', 'https') or not parsed.netloc:
        return None
    return base_url if base_url.endswith('/') else base_url + '/'


def _resolve_link_url(node: nodes.reference, ctx: _RenderContext) -> str | None:
    """Resolve a reference node's target to an absolute URL, if possible.

    Returns ``None`` for an unresolved target or when no base URL is
    configured.
    """
    refuri = node.get('refuri')
    if refuri and urlsplit(refuri).netloc:
        return refuri  # already absolute (an external hyperlink)

    base_url = _normalized_html_baseurl(ctx.app)
    if not base_url:
        return None
    current_page_url = urljoin(base_url, ctx.app.builder.get_target_uri(ctx.docname))

    if refuri:
        return urljoin(current_page_url, refuri)

    refid = node.get('refid')
    if refid:
        return f'{current_page_url}#{refid}'

    return None


def _add_comment(lines: list[str], text: str) -> None:
    """Append ``text`` to ``lines`` as one or more Python comment lines."""
    for line in text.splitlines():
        line_ = line.rstrip().translate(ASCII_REPLACEMENTS)
        lines.append(f'# {line_}' if line_ else '#')


# Doctest/code-block content is preformatted: RST markup (xref roles,
# hyperlinks) written inside a comment there passes through as raw text.
# These clean it up without touching real code.
_STRAY_XREF_RE = re.compile(r':(?:py:)?\w+:`([^`<>]+?)\s*(?:<[^<>]+>)?`')
_STRAY_HYPERLINK_RE = re.compile(r'`([^`<>]+?)\s*(?:<([^`<>]+)>)?`_+')


def _clean_stray_rst_markup(text: str) -> str:
    """Strip unparsed cross-reference/hyperlink RST syntax from a comment line."""
    text = _STRAY_XREF_RE.sub(r'\1', text)
    return _STRAY_HYPERLINK_RE.sub(
        lambda m: f'{m.group(1)} <{m.group(2)}>' if m.group(2) else m.group(1), text
    )


def _clean_code_comment(line: str) -> str:
    """Apply stray-markup cleanup and ASCII replacements to comment lines."""
    if line.lstrip().startswith('#'):
        line = _clean_stray_rst_markup(line)
        line = line.translate(ASCII_REPLACEMENTS)
    return line


def _render_reference(node: nodes.reference, ctx: _RenderContext) -> str:
    """Render a resolved or unresolved cross-reference/hyperlink.

    The target URL, if resolved, is used as a clickable markdown link in
    notebooks (always), and as literal URL text in ``.py`` (only within a
    "See Also" part or the footer -- elsewhere in ``.py`` the link is simply
    omitted).
    """
    display = node.astext()
    is_code = any(isinstance(child, nodes.literal) for child in node.children)
    url = _resolve_link_url(node, ctx)

    if url is None:
        return f'`{display}`' if is_code else display

    if ctx.fmt == 'ipynb':
        return f'[`{display}`]({url})' if is_code else f'[{display}]({url})'

    if ctx.in_see_also:
        # Surrounding newlines set this off on its own line; _add_comment
        # splits on them like any other multi-line text.
        return f'\n{display} {url}\n'

    if ctx.in_footer:
        # Inline, not surrounded by newlines -- "text url" in place, not a
        # markdown link.
        return f'{display} {url}'

    return f'`{display}`' if is_code else display


def _render_inline(node: nodes.Node, ctx: _RenderContext) -> str:
    """Render a node's inline content to a plain string.

    References go through ``_render_reference``. Other code-like spans
    (double-backtick literals, an unresolved reference's inner literal) are
    backtick-wrapped; everything else is flattened to plain text.
    """
    if isinstance(node, nodes.reference):
        return _render_reference(node, ctx)
    if isinstance(node, nodes.literal):
        return f'`{node.astext()}`'
    if isinstance(node, (nodes.image, nodes.figure, nodes.raw, nodes.comment)):
        return ''
    if isinstance(node, nodes.Text):
        return str(node)
    if hasattr(node, 'children') and node.children:
        return ''.join(_render_inline(child, ctx) for child in node.children)
    return node.astext()


def _join_segments(segments: list[Segment]) -> list[str]:
    """Flatten segments into lines, applying inter-segment spacing rules.

    - a blank line always follows a ``code`` segment, whatever comes next
    - a ``directive`` segment always gets a blank line both before and
      after it
    - otherwise (e.g. prose directly above a code block, or two prose
      segments back to back), no blank line is forced
    """
    lines: list[str] = []
    prev_kind: str | None = None
    for kind, seg_lines in segments:
        if not seg_lines:
            continue
        need_blank = prev_kind is not None and (
            prev_kind == 'code' or kind == 'directive' or prev_kind == 'directive'
        )
        if need_blank:
            lines.append('')
        lines.extend(seg_lines)
        prev_kind = kind
    return lines


def _convert_doctest_block(node: nodes.doctest_block) -> list[Segment]:
    """Convert a doctest block, stripping ``>>> ``/``... `` prompts.

    Non-prompted, non-blank lines are doctest *output* -- dropped entirely,
    not kept as comments.
    """
    lines: list[str] = []
    has_code = False
    for line in node.astext().splitlines():
        if line.startswith('>>> ') or line == '>>>':
            lines.append(_clean_code_comment(line[4:]))
            has_code = True
        elif line.startswith('... ') or line == '...':
            lines.append(_clean_code_comment(line[4:]))
        elif not line.strip():
            lines.append('')
        # else: doctest output line - dropped
    if not has_code:
        return []
    while lines and not lines[-1].strip():
        lines.pop()
    return [('code', lines)]


def _convert_literal_block(node: nodes.literal_block) -> list[Segment]:
    """Convert a ``.. code-block::``. Python blocks stay code, others become comments."""
    language = node.get('language', '')
    # Case-insensitive: sphinx-gallery emits ``.. code-block:: Python`` (capitalized).
    if language.lower() in _PYTHON_LANGUAGES:
        lines = [_clean_code_comment(line) for line in node.astext().splitlines()]
        while lines and not lines[-1].strip():
            lines.pop()
        return [('code', lines)] if lines else []
    text = node.astext().strip()
    if not text:
        return []
    comment_lines: list[str] = []
    _add_comment(comment_lines, text)
    # 'directive', not 'text': a non-Python literal block (e.g. an RST
    # ``::``-block illustrating a data format) gets blank lines on both
    # sides, same as any other directive.
    return [('directive', comment_lines)]


#: RST underline character per heading level, for ``.py`` output -- the
#: same sequence Sphinx's own documentation uses for sections, subsections,
#: subsubsections, paragraphs, and sub-paragraphs.
_TITLE_UNDERLINE_CHARS = {1: '=', 2: '-', 3: '~', 4: '^', 5: '"', 6: "'"}

#: Deepest heading level either heading style below can represent.
_MAX_HEADING_LEVEL = 6


def _title_underline_segment(title: str, level: int, fmt: str) -> Segment:
    """Build a heading directive segment for ``title`` at the given level.

    ``.py`` always uses an RST-style title + underline (e.g. ``# Title`` +
    ``# =====``), one character per level (see ``_TITLE_UNDERLINE_CHARS``);
    ``.ipynb`` always uses ATX ``#`` syntax instead (e.g. ``# ### Title``).
    """
    level = min(level, _MAX_HEADING_LEVEL)
    if fmt == 'ipynb':
        return ('directive', [f'# {"#" * level} {title}'])
    underline = _TITLE_UNDERLINE_CHARS[level] * len(title)
    return ('directive', [f'# {title}', f'# {underline}'])


def _heading_level(title: nodes.title) -> int:
    """Compute a title's heading level from its ``nodes.section`` nesting depth.

    Counts the title's own section and each ancestor ``nodes.section``.
    Running this on the file's own header would give level 1; a title
    nested inside that comes out level 2, one nested inside that comes out
    level 3, and so on -- clamped to ``_MAX_HEADING_LEVEL``.
    """
    level = 0
    node: nodes.Node | None = title.parent
    while isinstance(node, nodes.section):
        level += 1
        node = node.parent
    return min(level, _MAX_HEADING_LEVEL)


#: Extra indent for an admonition's content, under its ``# LABEL:`` line --
#: ``.py`` only (see ``_convert_admonition``).
_ADMONITION_CONTENT_INDENT = '    '


def _indent_comment_line(line: str) -> str:
    """Indent a ``# text`` comment line's content by ``_ADMONITION_CONTENT_INDENT``.

    A bare ``#``, a blank separator line (``''``), and a raw code line (no
    ``#`` prefix at all) all pass through unchanged.
    """
    if not line.startswith('# '):
        return line
    return f'# {_ADMONITION_CONTENT_INDENT}{line.removeprefix("# ")}'


def _is_raw_code_line(line: str) -> bool:
    """Check whether a rendered ``.py`` line is real code, not a ``#`` comment line."""
    return bool(line) and not line.startswith('#')


def _fill_comment_gaps(lines: list[str]) -> list[str]:
    """Turn a blank separator line into a bare ``#`` unless it borders raw code.

    ``_join_segments`` forces a blank line around some segment boundaries
    (e.g. a paragraph followed by a nested list) meant to visually separate
    unrelated top-level content. Folded into one ``# LABEL:`` comment block
    instead (see ``_indent_label_content``/``_definition_segment``), that
    same blank line needs a ``#`` to still read as part of that one block.
    A blank line bordering a raw code line (left flush and uncommented --
    see ``_convert_node``'s doctest/literal-block handling) stays blank,
    since that boundary really is between code and comment.
    """
    result: list[str] = []
    for i, line in enumerate(lines):
        if line != '':
            result.append(line)
            continue
        before = lines[i - 1] if i > 0 else ''
        after = lines[i + 1] if i + 1 < len(lines) else ''
        result.append(line if _is_raw_code_line(before) or _is_raw_code_line(after) else '#')
    return result


def _indent_label_content(lines: list[str], fmt: str) -> list[str]:
    """Indent every line after the first (a ``# LABEL:`` line) under it.

    ``.py`` only.
    """
    if fmt != 'py' or not lines:
        return lines
    label, *rest = _fill_comment_gaps(lines)
    return [label, *(_indent_comment_line(line) for line in rest)]


def _definition_segment(node: nodes.definition, ctx: _RenderContext) -> list[Segment]:
    """Convert a definition list's ``definition`` (its indented body), one level under its term.

    ``.py`` only, same as ``_indent_label_content``.
    """
    segments: list[Segment] = []
    for child in node.children:
        segments.extend(_convert_node(child, ctx))
    lines = _join_segments(segments)
    if ctx.fmt == 'py':
        lines = [_indent_comment_line(line) for line in _fill_comment_gaps(lines)]
    return [('text', lines)] if lines else []


def _list_segment(
    node: nodes.bullet_list | nodes.enumerated_list, ctx: _RenderContext
) -> list[Segment]:
    """Convert a bullet/enumerated list to one ``-``/``N.``-marked line per item.

    A blank line on both sides (``'directive'`` kind). A multi-line item's
    continuation lines get the same indent as an admonition's content.
    """
    ordered = isinstance(node, nodes.enumerated_list)
    lines: list[str] = []
    for index, item in enumerate(node.children, start=1):
        if not isinstance(item, nodes.list_item):
            continue
        item_segments: list[Segment] = []
        for child in item.children:
            item_segments.extend(_convert_node(child, ctx))
        item_lines = _join_segments(item_segments)
        if not item_lines:
            continue
        marker = f'{index}. ' if ordered else '- '
        first, *rest = item_lines
        first = f'# {marker}{first.removeprefix("# ")}' if first.startswith('# ') else first
        lines.append(first)
        lines.extend(_indent_comment_line(line) for line in rest)
    return [('directive', lines)] if lines else []


def _convert_admonition(
    node: nodes.Element, label: str, ctx: _RenderContext, *, skip_first_title: bool = False
) -> list[Segment]:
    """Convert an admonition-like container to a ``# LABEL:`` directive segment."""
    inner_ctx = replace(ctx, in_see_also=True) if label.upper() == 'SEE ALSO' else ctx
    inner: list[Segment] = [('text', [f'# {label}:'])]
    for child in node.children:
        if skip_first_title and isinstance(child, nodes.title):
            continue
        inner.extend(_convert_node(child, inner_ctx))
    lines = _indent_label_content(_join_segments(inner), ctx.fmt)
    return [('directive', lines)]


def _convert_node(node: nodes.Node, ctx: _RenderContext) -> list[Segment]:
    """Convert ``node`` into zero or more segments."""
    if any(_has_class(node, css_class) for css_class in _SKIP_SUBTREE_CLASSES):
        return []
    if isinstance(node, _IGNORED_TYPES):
        return []
    if isinstance(node, nodes.doctest_block):
        return _convert_doctest_block(node)
    if isinstance(node, nodes.literal_block):
        return _convert_literal_block(node)
    if type(node) in _ADMONITION_LABELS:
        if _is_see_also_type(node) and not ctx.show_see_also:
            return []
        return _convert_admonition(node, _ADMONITION_LABELS[type(node)], ctx)
    if _is_see_also_section(node):
        # a hand-written "See Also\n--------" heading nests as a full
        # section rather than a flat sibling - treat it like the
        # ``.. seealso::`` directive it's standing in for.
        if not ctx.show_see_also:
            return []
        return _convert_admonition(node, 'SEE ALSO', ctx, skip_first_title=True)
    if isinstance(node, nodes.admonition):
        # generic ``.. admonition:: Custom Title`` - use its own title as the label
        title_node = node.next_node(nodes.title)
        label = title_node.astext().strip() if title_node is not None else 'NOTE'
        return _convert_admonition(node, label, ctx, skip_first_title=True)
    if isinstance(node, nodes.title):
        # Gallery mode only: a sibling section's own heading (the page's own
        # outer title is filtered out before reaching here -- see
        # _process_gallery_page). Renders as a real Markdown heading in
        # .ipynb, at a level relative to its own section nesting (see
        # _heading_level).
        title_text = _render_inline(node, ctx).strip()
        level = _heading_level(node)
        return [_title_underline_segment(title_text, level, ctx.fmt)] if title_text else []
    if isinstance(node, nodes.definition):
        return _definition_segment(node, ctx)
    if isinstance(node, (nodes.bullet_list, nodes.enumerated_list)):
        return _list_segment(node, ctx)
    if isinstance(node, (*_CONTAINER_TYPES, nodes.section)):
        # nodes.section (gallery mode only): a sphinx-gallery ``# %%`` cell
        # with its own RST heading is a *sibling* section at the document
        # level, an ordinary child in a gallery page's span. Recursing
        # treats it like any other container: its title hits the
        # ``nodes.title`` case just above, its other children go through
        # the normal per-node conversion.
        segments: list[Segment] = []
        for child in node.children:
            segments.extend(_convert_node(child, ctx))
        return segments

    # Plain text-bearing nodes (paragraphs, etc.) - render inline content,
    # backticking code-like cross-references/literals along the way.
    text = _render_inline(node, ctx).strip()
    if not text:
        return []
    comment_lines: list[str] = []
    _add_comment(comment_lines, text)
    return [('text', comment_lines)]


def _has_real_code(source: str) -> bool:
    """Check whether ``source`` contains at least one executable statement."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return False

    return any(
        not isinstance(stmt, ast.Expr) or not isinstance(stmt.value, ast.Constant)
        for stmt in tree.body
    )


def _span_from(parent: nodes.Element, start: int) -> int:
    """Return the end index (exclusive) of a content span starting at ``start``.

    Extends until the next boundary-type node, or to the end of ``parent``'s
    children. A "See Also" heading/section is not treated as a boundary.
    """
    end = start
    for i in range(start, len(parent.children)):
        child = parent.children[i]
        if _is_see_also_heading(child) or _is_see_also_section(child):
            end = i + 1
            continue
        if isinstance(child, _BOUNDARY_TYPES):
            break
        end = i + 1
    return end


def _is_see_also_type(node: nodes.Node) -> bool:
    """Check whether ``node`` is a "See Also" admonition-type node (e.g. ``.. seealso::``)."""
    return type(node) in _ADMONITION_LABELS and _ADMONITION_LABELS[type(node)] == 'SEE ALSO'


def _see_also_in_desc_content(desc: addnodes.desc) -> nodes.Node | None:
    """Find a "See Also" admonition-type node among a ``desc`` node's own ``desc_content``."""
    content = next(
        (child for child in desc.children if isinstance(child, addnodes.desc_content)), None
    )
    if content is None:
        return None
    return next((child for child in content.children if _is_see_also_type(child)), None)


def _find_external_see_also(
    parent: nodes.Element, start: int, end: int, heading: nodes.Node
) -> nodes.Node | None:
    """Find a "See Also" part sited outside the normal ``[start, end)`` span.

    numpydoc's own "See Also" field is canonically reordered to sit before
    "Examples", as a sibling under ``parent``. If "Examples" was written as
    a real RST heading and hoisted out of its own ``desc_content`` to page
    level (see ``_enclosing_descs``), "See Also" -- not a ``nodes.section``,
    so untouched by that hoisting -- stays behind there instead, in the
    ``desc_content`` of the one ``desc`` that used to contain this heading.
    Only that nearest enclosing ``desc`` is checked -- not every one
    ``_enclosing_descs`` yields -- or a page listing several documented
    objects in a row would leak one object's "See Also" onto another's.
    """
    for i, child in enumerate(parent.children):
        if start <= i < end:
            continue
        if _is_see_also_type(child):
            return child
    desc = next(_enclosing_descs(heading), None)
    if desc is not None:
        return _see_also_in_desc_content(desc)
    return None


def _examples_spans(doctree: nodes.document) -> list[tuple[nodes.Element, int, int, nodes.Node]]:
    """Find every "Examples" heading's content span.

    Returns a list of ``(parent, start, end, heading)`` tuples.
    """
    spans = []
    for heading in doctree.findall(_is_examples_heading):
        parent = heading.parent
        start = parent.index(heading) + 1
        end = _span_from(parent, start)
        spans.append((parent, start, end, heading))
    return spans


def _desc_id(desc: addnodes.desc) -> str | None:
    """Pull the documented object's id (e.g. ``pkg.mod.func``) off a ``desc`` node."""
    signature = desc.next_node(addnodes.desc_signature)
    if signature is not None and signature.get('ids'):
        return signature['ids'][0]
    return None


def _enclosing_descs(node: nodes.Node) -> Iterator[addnodes.desc]:
    """Yield candidate ``desc`` nodes enclosing ``node``, closest first.

    At each ancestor level: the ancestor itself if it's a ``desc``, then
    the nearest preceding sibling ``desc`` under the same parent (an
    "Examples"/"See Also" section written as a real RST heading, not a
    bare ``.. rubric::``, ends up as a sibling of the object's own
    ``desc`` node rather than nested under it).
    """
    ancestor: nodes.Node | None = node.parent
    while ancestor is not None:
        if isinstance(ancestor, addnodes.desc):
            yield ancestor
        parent = ancestor.parent
        if parent is not None:
            index = parent.index(ancestor)
            for sibling in reversed(parent.children[:index]):
                if isinstance(sibling, addnodes.desc):
                    yield sibling
        ancestor = parent


def _qualified_name_for(node: nodes.Node, docname: str, counter: int) -> str:
    """Best-effort identifier used to name the generated file and its title header."""
    for desc in _enclosing_descs(node):
        desc_id = _desc_id(desc)
        if desc_id is not None:
            return desc_id
    base = Path(docname).name or docname
    return f'{base}-example-{counter}'


def _header_title(qualified_name: str) -> str:
    """Build the file's own header title text, e.g. ``Examples from pyvista.read``."""
    return f'Examples from {qualified_name}'


# A plain divider, not tied to any specific text's length the way a title
# underline is (see _title_underline_segment). Renders as a real <hr> in
# .ipynb once the '# ' prefix is stripped for a markdown cell.
_FOOTER_SEPARATOR = '-' * 70


def _footer_segment(footer: str | None, fmt: str, app: Sphinx, docname: str) -> list[Segment]:
    """Build the footer directive segment, if a footer is configured.

    Empty (0 or 1 elements, not a bare ``Segment | None``) so callers can
    just splat it into a segment list. Starts with ``_FOOTER_SEPARATOR``.

    Parsed as RST, the same as any other prose in this extension: a
    hyperlink written as ```` `text <url>`_ ```` becomes a real clickable
    Markdown link in ``.ipynb`` and inline "text url" in ``.py`` (see
    ``in_footer`` on ``_RenderContext``). Plain text with no RST markup at
    all becomes one comment line per line of text, blank-line-separated
    paragraphs kept apart. Only the *default* footer is one line/link (see
    ``_DEFAULT_FOOTER``).

    Parsed independently of the Sphinx build (plain docutils, not through
    Sphinx's own reader) -- only plain RST hyperlink syntax is supported,
    not Sphinx-specific roles like :func:/:class:.
    """
    if not footer:
        return []
    doctree = publish_doctree(footer, settings_overrides={'report_level': 5})
    ctx = _RenderContext(app=app, docname=docname, fmt=fmt, in_footer=True)
    segments: list[Segment] = []
    for node in doctree.children:
        segments.extend(_convert_node(node, ctx))
    lines = _join_segments(segments)
    return [('directive', [f'# {_FOOTER_SEPARATOR}', *lines])] if lines else []


def _strip_comment_prefix(line: str) -> str:
    """Remove the leading ``# `` (or bare ``#``) from a generated comment line."""
    if line == '#':
        return ''
    return line.removeprefix('# ') if line.startswith('# ') else line.removeprefix('#')


def _segments_to_cells(segments: list[Segment]) -> list[tuple[str, list[str]]]:
    """Group segments into notebook cells: consecutive runs become one cell each.

    A run of ``code`` segments becomes a code cell; a run of ``text``/
    ``directive`` segments becomes a markdown cell (same spacing rules as
    ``_join_segments``, with the ``#`` prefix stripped).
    """
    cells: list[tuple[str, list[str]]] = []
    run: list[Segment] = []
    run_kind: str | None = None

    def _flush() -> None:
        if not run:
            return
        joined = _join_segments(run)
        cells.append(
            (
                run_kind,
                [_strip_comment_prefix(line) for line in joined]
                if run_kind == 'markdown'
                else joined,
            )
        )

    for kind, lines in segments:
        if not lines:
            continue
        cell_kind = 'code' if kind == 'code' else 'markdown'
        if cell_kind != run_kind:
            _flush()
            run, run_kind = [], cell_kind
        run.append((kind, lines))
    _flush()
    return cells


def _cell_source(lines: list[str], kind: str) -> list[str]:
    r"""Format lines the way nbformat expects: each ending in ``\\n`` but the last.

    Markdown cells get a trailing hard line break (two spaces) on each
    non-blank line.
    """
    if not lines:
        return []
    if kind == 'markdown':
        lines = [f'{line}  ' if line else line for line in lines]
    return [f'{line}\n' for line in lines[:-1]] + [lines[-1]]


def _build_notebook(cells: list[tuple[str, list[str]]]) -> dict:
    """Build a minimal, valid nbformat-4.5 notebook dict from grouped cells."""
    nb_cells = []
    for i, (kind, lines) in enumerate(cells):
        cell: dict = {
            'cell_type': kind,
            'metadata': {},
            'source': _cell_source(lines, kind),
            'id': f'cell-{i}',
        }
        if kind == 'code':
            cell['execution_count'] = None
            cell['outputs'] = []
        nb_cells.append(cell)

    return {
        'cells': nb_cells,
        'metadata': {
            'kernelspec': {
                'display_name': 'Python 3',
                'language': 'python',
                'name': 'python3',
            },
            'language_info': {'name': 'python', 'pygments_lexer': 'ipython3'},
        },
        'nbformat': 4,
        'nbformat_minor': 5,
    }


def _write_download_file(app: Sphinx, name: str, extension: str, content: str) -> str:
    """Write generated content directly into the builder's downloads dir.

    Returns the written file's path relative to the downloads directory --
    the value to use as a ``download_reference``'s ``filename``.

    Writes straight to ``<outdir>/_downloads/...`` rather than registering
    through ``env.dlfiles``.
    """
    # 32 hex chars, matching Sphinx's own native _downloads/<digest>/... layout.
    digest = hashlib.sha256(content.encode()).hexdigest()[:32]
    safe_name = name.replace('.', '_') if name else 'example'
    filename = f'{safe_name}.{extension}'
    rel_path = f'{digest}/{filename}'

    out_path = Path(app.outdir) / '_downloads' / digest / filename
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding='utf-8')
    return rel_path


def _write_source(app: Sphinx, name: str, source: str) -> str:
    """Write a generated ``.py`` file; see ``_write_download_file``."""
    return _write_download_file(app, name, 'py', source)


def _write_notebook(app: Sphinx, name: str, notebook: dict) -> str:
    """Write a generated ``.ipynb`` file; see ``_write_download_file``."""
    return _write_download_file(app, name, 'ipynb', json.dumps(notebook, indent=1))


#: Default download link text per format -- see ``sphinx_examples_as_code_conf['link_labels']``.
_DEFAULT_LINK_LABELS = {
    'py': 'Download Python source code',
    'ipynb': 'Download Jupyter notebook',
}
#: The fixed order formats are offered in, regardless of how
#: ``sphinx_examples_as_code_conf['formats']`` lists them.
_FORMAT_ORDER = ('py', 'ipynb')


def _make_download_node(entries: list[tuple[str, str]]) -> nodes.paragraph:
    """Build one paragraph holding a download link for each ``(label, rel_path)`` entry."""
    paragraph = nodes.paragraph()
    for i, (label, rel_path) in enumerate(entries):
        if i > 0:
            paragraph += nodes.Text(' | ')
        reference = addnodes.download_reference('', reftarget=rel_path)
        reference['filename'] = rel_path
        reference += nodes.Text(label)
        paragraph += reference
    return paragraph


def _build_segments(nodes_in_span: list[nodes.Node], ctx: _RenderContext) -> list[Segment]:
    """Convert a span's nodes into segments.

    A bare ``.. rubric:: See Also`` heading isn't wrapped in a container the
    way ``.. seealso::`` or a nested section are: everything after it gets
    gathered into one merged directive segment instead.
    """
    segments: list[Segment] = []
    for i, node in enumerate(nodes_in_span):
        if isinstance(node, nodes.rubric) and _is_see_also_heading(node):
            if not ctx.show_see_also:
                break
            inner_ctx = replace(ctx, in_see_also=True)
            inner: list[Segment] = [('text', ['# SEE ALSO:'])]
            for later_node in nodes_in_span[i + 1 :]:
                inner.extend(_convert_node(later_node, inner_ctx))
            lines = _indent_label_content(_join_segments(inner), ctx.fmt)
            segments.append(('directive', lines))
            break
        segments.extend(_convert_node(node, ctx))
    return segments


def _build_download_entries(
    app: Sphinx,
    docname: str,
    name: str,
    header_title: str,
    nodes_in_span: list[nodes.Node],
    formats: list[str],
    footer: str | None,
    link_labels: dict[str, str],
    include_see_also: bool,
) -> list[tuple[str, str]]:
    """Convert a span of nodes into written ``.py``/``.ipynb`` files, per ``formats``.

    Returns ``(label, rel_path)`` entries for whichever formats are
    requested -- empty if the span has no real code, or ``formats`` itself
    is empty. Shared by the docstring-Examples path and gallery-page path;
    the only differences between them are how ``nodes_in_span``/``name``
    get built, and what ``header_title`` says (see ``_header_title`` vs.
    ``_process_gallery_page``'s own title handling). Always level 1 -- the
    file's own header is the one heading every generated file has exactly
    one of (see ``_title_underline_segment``).
    """
    py_ctx = _RenderContext(app=app, docname=docname, fmt='py', show_see_also=include_see_also)
    py_segments = _build_segments(nodes_in_span, py_ctx)

    if not any(kind == 'code' for kind, _lines in py_segments):
        return []

    py_header = _title_underline_segment(header_title, 1, 'py')
    py_segments_full = [py_header, *py_segments, *_footer_segment(footer, 'py', app, docname)]
    source = '\n'.join(_join_segments(py_segments_full)).rstrip() + '\n'

    if not _has_real_code(source):
        return []

    entries = []
    for fmt in _FORMAT_ORDER:
        if fmt not in formats:
            continue
        label = link_labels[fmt]
        if fmt == 'py':
            rel_path = _write_source(app, name, source)
        else:
            ipynb_ctx = _RenderContext(
                app=app, docname=docname, fmt='ipynb', show_see_also=include_see_also
            )
            ipynb_segments = _build_segments(nodes_in_span, ipynb_ctx)
            ipynb_header = _title_underline_segment(header_title, 1, 'ipynb')
            # Converted separately from the footer and concatenated, rather
            # than joined into one segment list and converted together --
            # the footer always gets its own dedicated cell this way.
            cells = _segments_to_cells([ipynb_header, *ipynb_segments])
            cells.extend(_segments_to_cells(_footer_segment(footer, 'ipynb', app, docname)))
            rel_path = _write_notebook(app, name, _build_notebook(cells))
        entries.append((label, rel_path))

    return entries


def _process_span(
    app: Sphinx,
    docname: str,
    parent: nodes.Element,
    start: int,
    end: int,
    heading: nodes.Node,
    counter: int,
    position: str,
    formats: list[str],
    footer: str | None,
    link_labels: dict[str, str],
    include_see_also: bool,
) -> None:
    """Convert one Examples span and insert download link(s) if it has real code."""
    nodes_in_span = list(parent.children[start:end])
    if include_see_also:
        external_see_also = _find_external_see_also(parent, start, end, heading)
        if external_see_also is not None:
            nodes_in_span.append(external_see_also)

    name = _qualified_name_for(heading, docname, counter)
    entries = _build_download_entries(
        app,
        docname,
        name,
        _header_title(name),
        nodes_in_span,
        formats,
        footer,
        link_labels,
        include_see_also,
    )
    if not entries:
        return

    download_node = _make_download_node(entries)
    parent.insert(start if position == 'top' else end, download_node)


# ---------------------------------------------------------------------------
# sphinx-gallery integration (opt-in via sphinx_examples_as_code_conf['gallery_downloads'])
# ---------------------------------------------------------------------------
#
# sphinx-gallery's own generated download links live in the doctree behind a
# handful of CSS classes (see gen_rst.py's DOWNLOAD_LINKS_HEADER and
# friends), matched against here instead of node type.

_GALLERY_NOTE_CLASS = 'sphx-glr-download-link-note'  # "go to the end to download" banner
_GALLERY_FOOTER_CLASS = 'sphx-glr-footer'  # the .py/.ipynb/.zip download links themselves
_GALLERY_TIMING_CLASS = 'sphx-glr-timing'  # "Total running time of the script: ..."
_GALLERY_SIGNATURE_CLASS = 'sphx-glr-signature'  # "Gallery generated by Sphinx-Gallery"

# Removed from the doctree entirely -- sphinx-gallery's own download UI,
# which our own link replaces. Timing/signature are deliberately *not* here:
# they stay on the rendered page (see _SKIP_SUBTREE_CLASSES for why they're
# still kept out of the generated download file).
_GALLERY_REMOVED_CLASSES = (_GALLERY_NOTE_CLASS, _GALLERY_FOOTER_CLASS)


def _strip_gallery_furniture(doctree: nodes.document) -> bool:
    """Remove sphinx-gallery's injected download note/footer, if present.

    Returns whether a download footer was found -- i.e. whether this page
    was actually generated by sphinx-gallery in the first place.
    """
    matches = list(
        doctree.findall(lambda n: any(_has_class(n, cls) for cls in _GALLERY_REMOVED_CLASSES))
    )
    found_footer = any(_has_class(node, _GALLERY_FOOTER_CLASS) for node in matches)
    for node in matches:
        if node.parent is not None:
            node.parent.remove(node)
    return found_footer


def _gallery_body(doctree: nodes.document) -> tuple[nodes.Element, int, int]:
    """Return ``(parent, start, end)`` spanning a gallery page's top-level sections.

    A sphinx-gallery page can have several top-level sections in a row (one
    per ``# %%`` cell with its own RST heading, each a sibling section at
    the document level). This spans all of them: from the first section
    found through the end of the document. Falls back to the document
    itself if there's no section at all.
    """
    first_section = next(doctree.findall(nodes.section), None)
    if first_section is None:
        return doctree, 0, len(doctree.children)
    return doctree, doctree.index(first_section), len(doctree.children)


def _gallery_example_name(docname: str) -> str:
    """Best-effort identifier for a gallery page, used to name its generated file(s)."""
    return Path(docname).name or docname


def _gallery_page_title(section: nodes.section) -> str | None:
    """Extract a gallery page's own title text, if it has one."""
    title_node = next((child for child in section.children if isinstance(child, nodes.title)), None)
    if title_node is None:
        return None
    return title_node.astext().strip() or None


def _process_gallery_page(
    app: Sphinx,
    docname: str,
    doctree: nodes.document,
    position: str,
    formats: list[str],
    footer: str | None,
    link_labels: dict[str, str],
    include_see_also: bool,
) -> None:
    """Replace a sphinx-gallery page's own download footer with converted downloads.

    A no-op for any page sphinx-gallery didn't generate, detected by the
    absence of its download footer.
    """
    if not _strip_gallery_furniture(doctree):
        return

    parent, start, end = _gallery_body(doctree)
    top_level = list(parent.children[start:end])
    if not top_level:
        return

    # The first top-level node is the page's own outer section (title,
    # intro, ...); its title is dropped (our own header replaces it) and
    # the rest of its children flattened into the span. Any further sibling
    # sections (one per "# %%" cell with its own heading) are kept as
    # sections, titles and all -- see _convert_node's nodes.section case.
    first, rest = top_level[0], top_level[1:]
    if isinstance(first, nodes.section):
        title = _gallery_page_title(first)
        nodes_in_span = [child for child in first.children if not isinstance(child, nodes.title)]
        nodes_in_span.extend(rest)
    else:
        title = None
        nodes_in_span = top_level

    name = _gallery_example_name(docname)
    # Uses the page's own title as the header, rather than "Examples from
    # <docname-derived name>". Falls back to the usual header if the page
    # has no title of its own.
    header_title = title if title else _header_title(name)
    entries = _build_download_entries(
        app,
        docname,
        name,
        header_title,
        nodes_in_span,
        formats,
        footer,
        link_labels,
        include_see_also,
    )
    if not entries:
        return

    download_node = _make_download_node(entries)
    if position == 'top' and isinstance(first, nodes.section):
        # Right after the page's own title -- matching what 'top' means for
        # a docstring Examples section -- not before the whole page/title.
        first.insert(1, download_node)
    else:
        parent.insert(start if position == 'top' else end, download_node)


def _process_doctree(app: Sphinx, doctree: nodes.document, docname: str) -> None:
    """Add a download link to every "Examples" section found on this page."""
    if not getattr(app.builder, 'download_support', False):
        # Only HTML-family builders serve a _downloads/ directory - skip
        # everything else (latex, text, man, epub, ...).
        return

    conf = app.config.sphinx_examples_as_code_conf
    position = conf['link_position']
    formats = conf['formats']
    footer = conf['footer']
    link_labels = conf['link_labels']
    include_see_also = conf['include_see_also']

    if conf['gallery_downloads']:
        _process_gallery_page(
            app, docname, doctree, position, formats, footer, link_labels, include_see_also
        )

    # Process spans per shared parent, last to first.
    spans = _examples_spans(doctree)
    numbered_spans = [(*span, i + 1) for i, span in enumerate(spans)]
    for parent, start, end, heading, counter in sorted(
        numbered_spans, key=lambda s: (id(s[0]), -s[1])
    ):
        _process_span(
            app,
            docname,
            parent,
            start,
            end,
            heading,
            counter,
            position,
            formats,
            footer,
            link_labels,
            include_see_also,
        )


# One line, one link.
_DEFAULT_FOOTER = (
    'Generated by `sphinx-examples-as-code <https://github.com/pyvista/sphinx-examples-as-code>`_'
)

#: Default value for every recognized ``sphinx_examples_as_code_conf`` key --
#: and the only keys it recognizes; anything else is a typo, caught at build
#: start rather than silently doing nothing.
_CONF_DEFAULTS: dict[str, object] = {
    'link_position': 'top',
    'formats': ['py', 'ipynb'],
    'gallery_downloads': False,
    'footer': _DEFAULT_FOOTER,
    'link_labels': _DEFAULT_LINK_LABELS,
    'include_see_also': True,
}


def _coerce_conf_value(key: str, value: object) -> object:
    """Coerce a value that may have arrived as a raw string; pass anything else through.

    A value set directly in ``conf.py`` already has its real Python type. A
    value set via ``-D sphinx_examples_as_code_conf.key=value`` on the
    command line always arrives as a plain string -- Sphinx's own type
    coercion for ``-D`` overrides (bool ``0``/``1``, comma-split lists, ...)
    only applies to a config value's top level, never to a dict's individual
    keys, so it's redone here for the two keys that need it.
    """
    if not isinstance(value, str):
        return value
    if key == 'formats':
        return value.split(',')
    if key in ('gallery_downloads', 'include_see_also'):
        if value == '0':
            return False
        if value == '1':
            return True
        msg = f"sphinx_examples_as_code_conf[{key!r}] must be '0' or '1', got {value!r}."
        raise ConfigError(msg)
    return value  # link_position, footer: a string is already the real type


def _merged_link_labels(value: object) -> dict[str, str]:
    """Merge a user-provided ``link_labels`` override over the defaults.

    A partial override (e.g. just ``{'py': 'Get the script'}``) only changes
    that one format's label; any not given keep their default.
    """
    if not isinstance(value, dict):
        msg = f"sphinx_examples_as_code_conf['link_labels'] must be a dict, got {value!r}."
        raise ConfigError(msg)
    unknown = sorted(set(value) - set(_DEFAULT_LINK_LABELS))
    if unknown:
        valid = ', '.join(sorted(_DEFAULT_LINK_LABELS))
        msg = (
            f"sphinx_examples_as_code_conf['link_labels'] has unknown key(s) {unknown} "
            f'(valid keys: {valid}).'
        )
        raise ConfigError(msg)
    return {**_DEFAULT_LINK_LABELS, **value}


def _finalize_conf(_app: Sphinx, config: Config) -> None:
    """Merge ``sphinx_examples_as_code_conf`` over the defaults, coerce it, and validate it.

    Runs once at ``config-inited``, so every other handler can just read
    ``app.config.sphinx_examples_as_code_conf[key]`` and get a fully-formed,
    correctly-typed dict back -- regardless of whether the user set it
    (fully, partially, or not at all) in ``conf.py``, via ``-D``, or both.
    """
    user_conf = config.sphinx_examples_as_code_conf
    unknown = sorted(set(user_conf) - set(_CONF_DEFAULTS))
    if unknown:
        valid = ', '.join(sorted(_CONF_DEFAULTS))
        msg = f'sphinx_examples_as_code_conf has unknown key(s) {unknown} (valid keys: {valid}).'
        raise ConfigError(msg)

    merged = dict(_CONF_DEFAULTS)
    merged.update((key, _coerce_conf_value(key, value)) for key, value in user_conf.items())
    merged['link_labels'] = _merged_link_labels(merged['link_labels'])
    config.sphinx_examples_as_code_conf = merged


def setup(app: Sphinx) -> dict:  # numpydoc ignore=RT01
    """Register the extension."""
    app.connect('doctree-resolved', _process_doctree)
    app.connect('config-inited', _finalize_conf)
    app.add_config_value('sphinx_examples_as_code_conf', {}, 'env')

    return {
        'version': __version__,
        'parallel_read_safe': True,
        'parallel_write_safe': True,
    }
